### ISSUE TITLE
Server NameErrors on noop_server.py:13

### ISSUE THREAD

**Issue by ghost** [mcrute/ubntmfi#1]
The server code will execute, but will NameError on line 13 once it receives an inbound connection:
`super(SimpleHTTPServer, self).__init__(*args, **kwargs)`

This is because SimpleHTTPServer isn't defined in the global namespace.

I think this should work instead. It unfortunately requires you name the base class, but, since SimpleHTTPRequestHandler doesn't appear to inherit from object (it's an old style class), you're not allowed to use super with its subclasses. 
`SimpleHTTPRequestHandler.__init__(self, *args, **kwargs)` 

Edit: Corrected - didn't realize SimpleHTTPRequestHandler was an old style class.

**Comment by mcrute** [comment]
Ooops. Thanks for the bug report. I just pushed a fix for the error.
